# for getting the dates of each lecture
CLASS_NUM: 10-405/10-605/10-805
DATES_WITH_NO_CLASS:
- [9, 7]
- [10, 12]
- [10, 14]
- [10, 16]
- [11, 25]
- [11, 27]
END_DATE: [12, 2]
LECTURE_DAY_OF_WEEK: 0
START_DATE: [8, 24]
YEAR: 2026
# for generating HTML version of schedule
BASEDIR: ..
SCHEDULE_FILE: schedule.html
HEADER: schedule_scripts/schedule_head.html
FOOTER: schedule_scripts/schedule_foot.html
