"""Build pq-papers-data.js for pq-papers.html: titles + author lists of arXiv cs.LG papers.

D (the dataset) = the first 4000 cs.LG papers submitted in Sept 2025,
Q (the queries) = the first 300 submitted in Sept 2026.

  python3 build_pq_papers_data.py                 # download into ./arx, then build
  python3 build_pq_papers_data.py --no-fetch      # rebuild from pages already in ./arx

The arXiv API answers Python's urllib with HTTP 406, so pages are downloaded with curl,
3 seconds apart as the API guidelines ask.
"""
import argparse, datetime, glob, json, os, re, subprocess, time
import xml.etree.ElementTree as ET

API = "https://export.arxiv.org/api/query"
NS = {"a": "http://www.w3.org/2005/Atom"}
SETS = {  # name: (submittedDate range, number of papers)
    "D": ("202509010000+TO+202509302359", 4000),
    "Q": ("202609010000+TO+202609302359", 300),
}
PAGE, MAX_AUTHORS = 1000, 30


def fetch(outdir):
    os.makedirs(outdir, exist_ok=True)
    for name, (dates, n) in SETS.items():
        for start in range(0, n, PAGE):
            url = (f"{API}?search_query=cat:cs.LG+AND+submittedDate:%5B{dates}%5D"
                   f"&start={start}&max_results={min(PAGE, n - start)}&sortBy=submittedDate&sortOrder=ascending")
            subprocess.run(["curl", "-sSf", "-m", "180", "-o", f"{outdir}/{name}{start}.xml", url], check=True)
            print(f"fetched {name} start={start}")
            time.sleep(3)


def parse(outdir, name):
    files = sorted(glob.glob(f"{outdir}/{name}*.xml"), key=lambda f: int(re.search(r"(\d+)\.xml$", f).group(1)))
    papers = []
    for f in files:
        for e in ET.parse(f).getroot().findall("a:entry", NS):
            title = re.sub(r"\s+", " ", e.findtext("a:title", "", NS)).strip()
            authors = [a.findtext("a:name", "", NS).strip() for a in e.findall("a:author", NS)]
            papers.append([title, authors[:MAX_AUTHORS]])
    return papers


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--arx", default="arx", help="directory for the downloaded API pages")
    ap.add_argument("--out", default="pq-papers-data.js")
    ap.add_argument("--no-fetch", action="store_true", help="use pages already in --arx")
    ap.add_argument("--date", default=datetime.date.today().isoformat(), help="fetch date recorded in the data")
    args = ap.parse_args()
    if not args.no_fetch:
        fetch(args.arx)
    data = {"D": parse(args.arx, "D"), "Q": parse(args.arx, "Q"),
            "source": f"arXiv cs.LG via export.arxiv.org API: D = first {SETS['D'][1]} papers submitted Sept 2025, "
                      f"Q = first {SETS['Q'][1]} submitted Sept 2026 (fetched {args.date})"}
    js = json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    with open(args.out, "w") as f:
        f.write(f"// Generated by build_pq_papers_data.py: titles + authors (first {MAX_AUTHORS}) of arXiv cs.LG papers.\n"
                f"const PAPERS = {js};\n")
    print(f"wrote {args.out}: D={len(data['D'])} Q={len(data['Q'])}")
